
void Clock(int a);
int about();
void colors();
void dimensions();
void window();
int applySettings(int toDo);
void mode();
void about2();
void numSystemsController();
void siPrefixController();
void actualTimeController();
double prefToNumber(char prefix);
void printTimer(int hours, int minutes, int seconds);
int letterVariables(char letter);
int firstLetterVariable(char letter);
int verifyLetter(char letter);
bool IsPreviousToWindowsVista();
int verifyNumber(char number);
int firstLetterFunction(char letter);
void openTxt();
void cls();
void wait(int seconds);
void on_start();
int datePreciser(double day, double month, double year, double dayS, double monthS, double yearS);
int verify4Printf(char chars);
int verifySpecifier(char chars);
