
void Clock(int a);
void colors();
void dimensions();
void window();
void mode();
void about2();
void numSystemsController();
void siPrefixController();
void actualTimeController();
void printTimer(int hours, int minutes, int seconds);
void printBigTimer(int hours, int minutes, int seconds);
void openTxt();
void cls();
int trackMouse();
void MouseMove(int x, int y);
void leftClick();
void wait(int seconds);
void on_start();
void addATCPath();
void getATCPath();
void ClearConsoleInputBuffer();
void graphSettings();
void getCharArray();
void clearKeyboardBuffer();
int toSolve(int re);
void ShowConsoleCursor(BOOL bShow);
void GetWindowPos(int *x, int *y, int *maxX, int *maxY);
void verboseResolutionController();
void complexNumber(double a, double b);
void idColorToName(char color);
void show(HWND hwnd);
int getReady();
void microeconomicsCalculations();
boolean letterVariables(char letter);
boolean firstLetterVariable(char letter);
boolean verifyLetter(char letter);
boolean about();
boolean verifyNumber(char number);
boolean firstLetterFunction(char letter);
boolean verify4Printf(char chars);
boolean verifySpecifier(char chars);
boolean verifyNumerical(char number);
boolean isSolved();
boolean verifyValue(char number);
boolean IsPreviousToWindowsVista();
int datePreciser(double day, double month, double year, double dayS, double monthS, double yearS);
int applySettings(int toDo);
double prefToNumber(char prefix);
char character_to_prefDet(double n);

