

void cotan(double x, double y);
void sec(double x, double y);
void cosec(double x, double y);
void cotanh(double x, double y);
void sech(double x, double y);
void cosech(double x, double y);
void sinc(double x, double y);
double ln(double z);
void arsinh(double x, double y);
void arcosh(double x, double y);
void artanh(double x, double y);
void arcoth(double x, double y);
void arsech(double x, double y);
void arcsch(double x, double y);
double pot(double base, double exponent, int sig);
double re(double dividend, double divider);
double qu(double dividend, double divider);
void arcosec(double x, double y);
void arcsec(double x, double y);
void arcotg(double x, double y);
double multi(double multip);
double quo(double quotient);
double fl(double number);
double returnDeciPart(double number);
double qfunc(double x);
double qfuncinv(double p);
double gerror(double q);
double gerrorinv(double e);
double gerrorc(double q);
double gerrorcinv(double a);
double rt(double radicand, double degree, int sig);
double arcfact(double f);
void complex_log(double a, double b);
void qu_complex(double dividend, double dividendI, double divider, double dividerI);
void re_complex(double dividend, double dividendI, double divider, double dividerI);
void complex_cos(double x, double y);
void complex_sin(double x, double y);
void complex_tan(double x, double y);
void complex_cosh(double x, double y);
void complex_sinh(double x, double y);
void complex_tanh(double x, double y);
void complex_asin(double x, double y);
void complex_acos(double x, double y);
void complex_atan(double x, double y);
void round_complex();
void solveSystem();
void rearrangeValues();
void getSolutions();
void sum(double numR, double numI, double denR, double denI);
void subtraction(double numR, double numI, double denR, double denI);
void multiplication(double numR, double numI, double denR, double denI);
void division(double numR, double numI, double denR, double denI);
double fact(double d);
void exponentiation(double a, double b, double c, double d, int sig);
double arg(double a, double b);